server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: inventario-service
          uri: lb://INVENTARIO
          predicates:
            - Path=/api/v1/productos/**

        - id: client-order-service
          uri: lb://PEDIDOSCLIENTE
          predicates:
            - Path=/api/v1/pedidos-cliente/**

        - id: provider-order-service
          uri: lb://PEDIDOSPROVEEDOR
          predicates:
            - Path=/api/v1/pedidos-proveedor/**

        - id: invoice-client-service
          uri: lb://FACTURACION
          predicates:
            - Path=/api/v1/facturas-cliente/**

        - id: invoice-provider-service
          uri: lb://FACTURACION
          predicates:
            - Path=/api/v1/facturas-proveedor/**

management:
  endpoints:
    web:
      exposure:
        include: gateway,health,info,metrics
  endpoint:
    gateway:
      enabled: true
    health:
      show-details: always


