server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info,beans,mappings,metrics,httptrace,env,threaddump,loggers,conditions,gateway
  gateway:
    access: read-only
    enabled: true
  endpoint:
    health:
      show-details: always


