server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: inventario
          uri: http://localhost:8083
          predicates:
            - Path=/inventario/**
          filters:
            - StripPrefix=1
        - id: pedidoscliente
          uri: http://localhost:8082
          predicates:
            - Path=/pedidoscliente/**
          filters:
            - StripPrefix=1
        - id: pedidosproveedor
          uri: http://localhost:8084
          predicates:
            - Path=/pedidosproveedor/**
          filters:
            - StripPrefix=1
        - id: facturacion
          uri: http://localhost:8088
          predicates:
            - Path=/facturacion/**
          filters:
            - StripPrefix=1

management:
  endpoints:
    web:
      exposure:
        include: "*"
